### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by jimzhu** [logpai/logparser#1]
1. Fix TODO in SHISO_demo
2. Finish docs/reference.md
3. Finish benchmark settings, especially regex, and double-check parameters (e.g. Spell)

**Comment by PunyTitan** [comment]
Thanks for reaching out!

Currently, we haven't uploaded the source code of "Spell", which is
regarded a future work in our plan list. However, if you want to find an
online log parser, you could try our method DrainV1 released in the project
page.

Regards,
Pinjia
