### ISSUE TITLE
Unable to reproduce benchmark results

### ISSUE THREAD

**Issue by AgrawalAmey** [logpai/logparser#10]
Hi,

I have been trying to recreate the performance benchmarks described in Drain extended (https://arxiv.org/pdf/1806.04356.pdf). I am using the `benchmark/Drain_benchmark.py` script on`dev` branch. I am using the full edition log files instead of the 2k versions and have commented out the f1 measure and accuracy computation part. The full script is at `https://pastebin.com/aLVhkTeQ`. On my macbook pro 2.2GHz i7 system the HDFS task takes ~3200 seconds as opposed to the ~100 seconds as shown in the paper. Should I be changing some settings/CPU?

**Comment by PinjiaHe** [comment]
Thanks for reaching out!

The script you used is the implementation of the non-extended version of Drain, which is reported in our ICWS17 paper. If you take a look at the Drain extended paper, you will find that it does not require parameter tuning effort. However, for the script you attached, there are parameters like "st" and "depth", which are required by the non-extended version.

**Comment by AgrawalAmey** [comment]
Thanks for the quick response. Could you guide me about how can I benchmark Drain extended?

**Comment by AgrawalAmey** [comment]
I tried modifying `Drain.py` in `master` branch as https://pastebin.com/yiaRzQUB but got the following error,
`ValueError: invalid literal for int() with base 10: '460903 resourcemgmtdaeomon node-25 server subsys 1145552216 1 failed to configure resourcemgmt subsystem err = 10\r\n'`

**Comment by AgrawalAmey** [comment]
Since there is no example script using drain, I tried to guess some parameters. Could you please verify these,
```
RawLogPath = '../../logpai_dataset'
RawLogFile = '/HDFS.log'
OutputPath = './results/'
removeCol = [0,1,2,3,4]
rex = [('blk_(|-)[0-9]+', 'blkID'), ('(/|)([0-9]+\.){3}[0-9]+(:[0-9]+|)(:|)', 'IPAddandPortID')]
mt = 1
delimiters = '\s+'
para=Para(path=RawLogPath, logName=RawLogFile, savePath=OutputPath, rex=rex, mt=mt, delimiters=delimiters, removeCol=removeCol)
 
myparser=Drain(para)
time=myparser.mainProcess()
```

Thank you.

**Comment by PinjiaHe** [comment]
The parameters depend on your experimental settings. For example, the path related parameters depends on where you store the input/output data. The overall logic of this script should be corrent.

Thanks.

**Comment by AgrawalAmey** [comment]
The issue was that the same datasets have an index column whereas the raw datasets did not. Small change in the splitting logic fixed it. Thanks.

**Comment by NilsDeckert** [comment]
Hey @PinjiaHe, I'm curious why only the ICWS'17 version of Drain is included here and not the extended and improved version?
An implementation is available in the dev branch with the old API, but it seems like it didn't make it to master.

**Comment by xpai** [comment]
The logparser library is mainly for research and benchmarking purposes. The improved version is based on Spark. It becomes hard to maintain due to Spark version updates.
