### ISSUE TITLE
How does the logpai/Drain3 repository compare to the implementation in this repository?

### ISSUE THREAD

**Issue by AdrianIssott** [logpai/logparser#106]
In particular, is https://github.com/logpai/Drain3 more up-to-date or otherwise preferred compared to https://github.com/logpai/logparser/tree/main/logparser/Drain? The two implementations are different despite having the same name.

**Comment by zhujiem** [comment]
If you want to use it for research, please use logparser/Drain, which is our prototype implementation. If you want to use it for production logs, please consider Drain3.
