### ISSUE TITLE
Inconsistency with Templates and the EventTemplates in the Spark2k_corrected version file 

### ISSUE THREAD

**Issue by WahomeKezia** [logpai/logparser#116]
Hii there ! 

I wanted ask and clarify about eventTemplates  with urls and file paths (using Spark logs)

`E6 `| Connecting to driver: spark://<*>

`E12` | Input split: hdfs://<*>

`E25 `| Saved output of task 'attempt_<*>' to hdfs://<*>

`E23` | Remoting started; listening on addresses :[akka.tcp://<*>]

I have noted on the corrected version, the logs in the structured csv have different templates from the eventTemplate csv file 

eg.. here is a log , eventTemplate label and the template 
Input split: hdfs://10.10.34.11:9000/pjhe/logs/2kSOSP.log:21876+7292 | `E12 ` | `Input split: <*>`

**Comment by zhujiem** [comment]
Sorry, I did not understand your problem.

**Comment by WahomeKezia** [comment]
Hii @zhujiem , 
Like in this log example , Input split: hdfs://10.10.34.11:9000/pjhe/logs/2kSOSP.log:21876+7292 | `E12` | I`nput split: <*>`

It's eventtemplate 12 ,` Input split: <*>` and  on this file [Spark_2k.log_templates.csv](https://github.com/logpai/logparser/blob/main/data/loghub_2k_corrected/Spark/Spark_2k.log_templates.csv)

the EventTemplate 12 is slightly different

**Comment by zhujiem** [comment]
In the [loghub_2k_corrected](https://github.com/logpai/logparser/tree/main/data/loghub_2k_corrected), you should refer to *_structured_corrected.csv and *_templates_corrected.csv, which are the corrected versions.
So, E12 should be:
```
E12	Input split: <*>
```

**Comment by WahomeKezia** [comment]
Ooh ,I see . Thank you! @zhujiem
