### ISSUE TITLE
Persistence for logparser.Brain?

### ISSUE THREAD

**Issue by AdaptiveStep** [logpai/logparser#118]
two quick questions:
1: Drain3 has persistence with File/redis/kafka. How to set persistence up with brain? Is it possible?

2: Drain3 also has livestream inputs with sdin. I cannot find any documentation on this for Brain. Is it possible to do with Brain?

**Comment by zhujiem** [comment]
Drain3 is a third-party library maintained by [davidohana](https://github.com/davidohana). We currently have no plan to add persistence to Brain. Thanks!
