### ISSUE TITLE
[Question] Finding best Drain parameters

### ISSUE THREAD

**Issue by thomasryck** [logpai/logparser#17]
I was thinking to use genetic algorithms in order to find the best Drain parameters. Do you think that it is useless to use such time consuming algorithms for this problem or could it be worth it ? Did you use optimization algorithms to find the best parameters when benchmarking Drain ? And if yes, which one ?

**Comment by jimzhu** [comment]
Automatic parameter tuning is indeed a good point for log parsers. During benchmarking, we use simple grid search. We also released an ongoing work with automatic tuning with heuristics on arxiv. You may have a look. But I do not know how  genetic algorithms will perform.

**Comment by thomasryck** [comment]
Can you please provide me the link to the paper ? And close the issue ?

**Comment by PinjiaHe** [comment]
Our preprint is here: [https://arxiv.org/abs/1806.04356](https://arxiv.org/abs/1806.04356)

**Comment by thomasryck** [comment]
I understand that the Drain described in this paper is different from the one available in this repository. Is the implementation of the "new" Drain available somewhere ?

**Comment by thomasryck** [comment]
Is that correct that the last version of Drain is the file Drainjournal.py
