### ISSUE TITLE
Can not find how to create logTemplateMap.csv file

### ISSUE THREAD

**Issue by PriyankBangar** [logpai/logparser#2]
Hello,

I was working with your SVM_BGL.py file and this file asks for a logTemplateMap.csv. I am not able to figure out from looking into your log parser library, as from where is this file generated. Any help would be appreciated.

Thank you

**Comment by ShilinHe** [comment]
Hi, actually logTemplateMap.csv is a list of log<=>log_event mappings. After log parsing, each log (with index number) has its corresponding log event (represented with a event index). It is not directly generated from the logparser, but it can be easily generated to store the mappings. We will update the logizer in recent days, you may refer to that repository.

**Comment by NooPliskin** [comment]
Excuse me where can I find the logTemplateMap.csv file? Or in case he can explain to me exactly how to create it? Thank you.

**Comment by ShilinHe** [comment]
Now you can find the logTemplateMap.csv in the logizer project, under the directory of bgl_demo
