### ISSUE TITLE
Drain EventId displays hexdecimal values

### ISSUE THREAD

**Issue by IllidanStromrage** [logpai/logparser#20]
I am using the Drain logparser and I observed that the EventId always displays hexadecimal equivalent of the hash when written to the .csv files. Can it be instead represented as events 1, 2, 3,... and so on? I am using Python 3.7.

**Comment by jimzhu** [comment]
Yes. It is a design choice for easy maintainance of templates in production. We found it is hard to maintain a global counter for that. But for experimentation, if you prefer to use numbers, use can perform postprocessing.
