### ISSUE TITLE
Bug in Spell.py SimpleLoopMatch()

### ISSUE THREAD

**Issue by okingniko** [logpai/logparser#21]
The original code snippet is below:
```python
    def SimpleLoopMatch(self, logClustL, seq):
        retLogClust = None

        for logClust in logClustL:
            if float(len(logClust.logTemplate)) < 0.5 * len(seq):
                continue
            
            #If the template is a subsequence of seq
            it = iter(seq)
            if all(token in seq or token == '*' for token in logClust.logTemplate):
                return logClust

        return retLogClust
```

But in Spell's article, the explanation of the steps is as follows:
```
1) Simple loop approach. A naive method is to simply loop
through strs. For each stri, maintain a pointer pi pointing to
the head of stri, and another pointer pt pointing to the head
of σ. If the characters (or tokens in our case) pointed to by pi
and pt match, advance both pointers; otherwise only advance
pointer pt. When pt has gone to the end of σ, check if pi has
also reached the end of stri. A pruning can be applied which
is to skip stri if its length is less than 1|σ|. The worst time 2
complexity for this approach is O(m · n).
```

so you may compare the input string and template strings(in LCAObjects) by order, for your implementation, you only check whether the token is exists in input string.

Hava a nice day.

**Comment by jimzhu** [comment]
Thanks for raising the issue. Yes, the original code is to check the template is a subsequence of seq. But we use set checking as a proxy here for speedup since we found that logs with same tokens but different orderings rarely occur in logs.

**Comment by okingniko** [comment]
ok, thanks for quick reply, I got it . After PrefixMatchCheck, use token exists check is interpretable.
