### ISSUE TITLE
Sort Output

### ISSUE THREAD

**Issue by SoftBanX** [logpai/logparser#23]
Excellent -nHow do you sort the output on say occurrences descending?

thanks

**Comment by jimzhu** [comment]
What did you mean? We have a file for event occurrences.

**Comment by SoftBanX** [comment]
List CSV output with occurrence descending 


EventId | EventTemplate | Occurrences
-- | -- | --
c9397c3d | PacketResponder for block terminating | 311
5fd4a9f7 | BLOCK* NameSystem.addStoredBlock: blockMap updated: is added to size 67108864 | 314


Great work anyhow

**Comment by jimzhu** [comment]
Thanks! The templates.csv is usually not so big, so it can be easily sorted using excel.
