### ISSUE TITLE
How to extract the matched data during parsing process

### ISSUE THREAD

**Issue by white2018** [logpai/logparser#25]
@jimzhu Excellent work!

Since logparser is able to output the structured data and template expression like '<*>'. I would like to know how to write a function with the input of line and template expression, and returns the list of matched elements. The definition of function is as follows:

def extract_data(line, expression):
    return list_of_matched_data

For example:

input:
    #line: [52187162.990775] sd 0:0:7:0: attempting task abort! scmd(ffff88219e405b80)
    #expression: [<*>.<*>] <*> <*> attempting task abort! <*>
output:
    ['52187162', '990775', 'sd', '0:0:7:0', 'scmd(ffff88219e405b80)']

Thanks a lot

**Comment by jimzhu** [comment]
Please follow logmatch_demo.py to get the parameter list.

**Comment by white2018** [comment]
> 
> 
> Please follow logmatch_demo.py to get the parameter list.

It is really good about logmatch_demo.py!

Thanks a lot!

**Comment by jimzhu** [comment]
Thanks for your comments!
