### ISSUE TITLE
the problem of templates.csv is generated by Spell.py

### ISSUE THREAD

**Issue by white2018** [logpai/logparser#26]
Hi, @jimzhu 

The templates.csv generated by Drain.py works fine with regexmatch.py. which is to run Drain_demo.py and logmatch_demo.py in order. However, Spell_demo.py does not match regexmatch.py.

I compare the templates created by Drain.py with that of Spell.py respectively. The big difference is '*'.

Here is the example templates with respect to HDFS_2k.log

The templates corresponding to Drain_demo.py
EventId,EventTemplate,Occurrences
dc2c74b7,PacketResponder <*> for block <*> terminating,311
5d5de21c,BLOCK* NameSystem.addStoredBlock: blockMap updated: <*> is added to <*> size <*>,314
e3df2680,Received block <*> of size <*> from <*>,292
09a53393,Receiving block <*> src: <*> dest: <*>,292

The templates corresponding to Spell_demo.py
EventId,EventTemplate,Occurrences
5b95a418,* * for * * *,331
3949a200,BLOCK* * * * * *,659
67f0912e,Received block * of size * *,294
f7a1dcba,Receiving block * src * dest *,292
a8cc20dc,Deleting block * file *,263
94eb1881,* Served block * to *,80

Do I miss something which leads to such problem? Thanks

**Comment by white2018** [comment]
I think this issue could be fixed easily.

Thanks a lot

**Comment by jimzhu** [comment]
> I think this issue could be fixed easily.
> 
> Thanks a lot

Thanks for your comments! We have updated the code to support parameter list extraction of the four best log parsers: Drain, Spell, IPLoM, and AEL. You can run the demo scripts again.
