### ISSUE TITLE
How to save the tree in the method "Drain" ?

### ISSUE THREAD

**Issue by xljhtq** [logpai/logparser#27]
When trained based on large numbers of logs,  how the tree model can be saved in "DRAIN"?
Just by transforming it into string ??

**Comment by PinjiaHe** [comment]
The current version provides a "printTree" method that can print a tree. You could also implement a specialized method according to your needs.

**Comment by imSrbh** [comment]
printTree() is a recursive function.
it wasn't called anyhwere???
what params to be passed??
@PinjiaHe @xljhtq @zhujiem @ShilinHe @JinYang88
