### ISSUE TITLE
Parsing in a streaming manner

### ISSUE THREAD

**Issue by amineebenamor** [logpai/logparser#28]
Hello,
I need to implement Drain (or Spell, but Drain seems to have better results) to parse logs in a streaming and timely manner to make a real-time predictive maintenance pipeline.
I read several times the code, it seems like right now the streaming manner to make a
centralized server that contains a log parser is not implemented right now, but the functions that already exist may help to do it.
For adding new logs to old parsed logs, I think that the variable "logCluL" (in Drain code) needs to be loaded from the template csv file (of the old logs) which contains the templates and rebuild the tree from the structured csv file. After that, new logs are added in the tree and each log is a new line which is appended in the structured and template csv files.
This approach seems to be good for a few runs of the parser, but not for a streaming manner where a server contains a log parser.
In my opinion, such a server needs to have the tree with the templates always in memory (RAM) but writing the logs in real-time in a database (to free the RAM usage). Maybe some blocks of the Drain code can help to do that.
Do you have another approach to propose?
Did you make any implementation of the online streaming manner that can help me?
Thank you for your answer!

**Comment by PinjiaHe** [comment]
> such a server needs to have the tree with the templates always in memory (RAM) but writing the logs in real-time in a database (to free the RAM usage)

Yes, I also think this is the right way to go. We could keep only "logTemplate" in RAM for online parsing. 

> Did you make any implementation of the online streaming manner that can help me?

Currently, we don't have such implementation (i.e., keep only templates in RAM while outputing logs to database), but that is an important future work. We also welcome your contribution on this. 

Thanks.

**Comment by jimzhu** [comment]
@amineebenamor Stream log parser is indeed a practical requirement. It also needs a model recovery when a crash occurs. We actually have implemented this feature in an enterprise project, but we cannot release that at current stage. Implementing the streaming log parser is not too hard. I think a good solution is to extract log templates offline (hourly or daily) and periodically dump the events templates into file. Then, for the online part, you could call the logmatch API in "logmatch_demo.py", which use template.csv as input, and leverage regular expressions to quickly parse logs in a stream manner. In case the stream produce too many logs, the logmatch can be even parallelized into multiple processes. Meanwhile, parsing logs using logmatch (with optimized regrex search) is much efficient than offline algorithms for template extraction. Hope this helps you.

**Comment by amineebenamor** [comment]
Thank you very much for your answers!
I see what you're talking about, I've read the part concerning LogKit (System X) in your paper: well done!
I'll follow your advice and try to make it, I'll let you know if I have any trouble.
Thank you again for your help @jimzhu @PinjiaHe !

**Comment by amineebenamor** [comment]
Hello @jimzhu ,
I can't find anywhere your paper "Real-Time Log Event Matching at Scale":
`Jieming Zhu, Jingyang Liu, Pinjia He, Zibin Zheng, Michael R. Lyu. "Real-Time Log Event Matching at Scale", XXX, 2018.`
Is there a way/link to have it please?
Thank you in advance!

**Comment by jimzhu** [comment]
Sorry,  this paper has not been started yet. But it is still in our plan.

**Comment by amineebenamor** [comment]
The year of the paper is "2018" that's why I thought it was already written but you maybe just forgot to update the year. I understand that there's still a lot to do and it takes time too :)
Thank you for your answer!

**Comment by amineebenamor** [comment]
> @amineebenamor Stream log parser is indeed a practical requirement. It also needs a model recovery when a crash occurs. We actually have implemented this feature in an enterprise project, but we cannot release that at current stage. Implementing the streaming log parser is not too hard. I think a good solution is to extract log templates offline (hourly or daily) and periodically dump the events templates into file. Then, for the online part, you could call the logmatch API in "logmatch_demo.py", which use template.csv as input, and leverage regular expressions to quickly parse logs in a stream manner. In case the stream produce too many logs, the logmatch can be even parallelized into multiple processes. Meanwhile, parsing logs using logmatch (with optimized regrex search) is much efficient than offline algorithms for template extraction. Hope this helps you.

Your answer helped me to start parsing in a streaming manner, but I'm still wondering what should be done with logs that are not matched to any templates, particularly if these are new keys that will be for example considered as an anomaly. These are very important logs that need to be matched.
Would the extraction of log templates offline be on logs that haven't been matched with log match API?
It would be a few logs and parsing them will be fast.
Is there a particular way to do it rather than writing them in a file?
Thank you for your answer!
