### ISSUE TITLE
no code of pop

### ISSUE THREAD

**Issue by xiaoze17** [logpai/logparser#29]
In your TDSC(2018) "Towards automated log parsing for large-scale log data analysis", you said your team has published the source code of POP. However, I didn't find that.

**Comment by jimzhu** [comment]
https://github.com/logpai/logparser/tree/dev/logparser/POP

We have not yet added it to master since the doc is incomplete.

**Comment by jimzhu** [comment]
https://github.com/logpai/logparser/tree/dev/logparser/POP  It is in the dev branch.
