### ISSUE TITLE
Drain outcome dependent on line order?

### ISSUE THREAD

**Issue by kokonguyen191** [logpai/logparser#31]
Does Drain return the same templates if the lines in a log file are swapped around, say, lines 1 2 3 4 become 4 2 1 3? My intuition says no but I haven't fully understood the implementation to be able to say it with certainty.

**Comment by PinjiaHe** [comment]
Thanks for your question. Theoretically, the output templates could be different if the log lines were swapped. In practice, based on our experiences working with the provided datasets, the order has little impact on the parsing results.
