### ISSUE TITLE
How do we get parameterised key-value pairs in Drain?

### ISSUE THREAD

**Issue by AnkitNassa** [logpai/logparser#32]
Hi,

I have a requirement where i want the log sources after parsing automatically gets associated to some key. For instance if the log source is:
Sent 200KB from 1.1.1.1 to 2.2.2.2
 I would like to create a json with following details:
properties{
"bytes_sent" : "200KB",
"srcIpV4" : 1.1.1.1,
"destIpV4" : 2.2.2.2
}

Can you please suggest a way if we can do something like these with Drain?

**Comment by kokonguyen191** [comment]
If you get a template like

```
Sent <*> from <*> to <*>
```

The structured CSV should have something like

```
LineId,Content,EventId,EventTemplate,ParameterList
0,Sent 200KB from 1.1.1.1 to 2.2.2.2,abcdef,Sent <*> from <*> to <*>,['200KB','1.1.1.1','2.2.2.2']
```

After that, you can create a small script to generate your desired output.

**Comment by AnkitNassa** [comment]
Thanks @kokonguyen191 .
