### ISSUE TITLE
Speed up Drain

### ISSUE THREAD

**Issue by kokonguyen191** [logpai/logparser#33]
Is there any way to speed up the parsing process? After parsing 4 million lines, the speed is down to around 30k lines/hour, which in my use case is too slow to be useful. Any idea is appreciated.

**Comment by PinjiaHe** [comment]
One possible reason is too many unnecessary log groups have been generated during the process, which leads to long search time.

Maybe you could take a look at the current log groups/templates, and see if there are some that could be handled by preprocessing scripts.

**Comment by kokonguyen191** [comment]
I have around 2000 templates as I am working with generic logs. Is is possible to parallelize any part of the code to improve the speed?

**Comment by amineebenamor** [comment]
I agree I have the same issue.
In my case, when I run it on big files (around 31 million lines), the function "log_to_dataframe" takes most of the time (more than 10 hours). The real parsing part takes around 10% of the total time of Drain execution (only one hour).

**Comment by PinjiaHe** [comment]
Thanks for the feedback. Yes, the current implementation of _log_to_datraframe_ will read all the logs to a list, which may cause slow speed for very large input. One possible way to improve this is to use "with open() as lines:" to read logs one by one, only retains the templates during parsing, and output the logs in streaming style.

For parallelization, in principle, Drain can be parallelized. We could put the searching part in multiple nodes, and the update of the tree in a master node (while local nodes maintain a local tree). The trees could be synchronized when any of the trees have new templates. This implementation should require some coding effort.

**Comment by jimzhu** [comment]
Using drain to parse a single large log file (say 1GB) is doable, but not recommended. We suggest you to partition you large log file into small files (say 100MB), and run Drain one by one. For demonstration purpose, we save the structured log file as a csv. It does not perform well for large files. 

If you are looking for some efficient solutions to run Drain in industry, you'd better consider it as a two-phase process. Actually, we run an *offline* module to extract event templates using Drain.  The *online* module is an optimized regrex matching process using the event tempaltes updated by the offline module. The building of the whole solution needs some system engineering work. We use kafka and redis for this. But the online parsing script is under *logparser/demo/logmatch_demo.py*

**Comment by riyu94** [comment]
Hi @jimzhu, your method of using kafka and redis seems reliable for online log parsing. Can you elaborate more on the online drain process and offline process of extracting the templates. 
According to my understanding,

Suppose, I partition the large file into small files of 100MB, pass it through Drain, get the templates csv file as output and use this file iteratively for online parsing of further logs (with kafka and redis).
How often can I update this template file and how?

**Comment by prateekiiest** [comment]
Hi, has there been any solution to this?
