### ISSUE TITLE
How to handle logs separated by special characters(|,) in Drain

### ISSUE THREAD

**Issue by AnkitNassa** [logpai/logparser#34]
Hi Team,

I have few log samples which belongs to same log pattern, i.e. they should have only 1 template because the nature of their pattern. When i run them against Drain Algorithm, i see that each log line generates a new template. This is happening because we are splitting on the basis of space. But if the log line is splitted on the basis of special characters, we have different templates. Is there anyway where we can fix this as part of code? May be split by | or comma and then by space?

For instance checkout the following log files as attached.
[Comma_Separated_Logs.txt](https://github.com/logpai/logparser/files/3305497/Comma_Separated_Logs.txt)
[Pipe_Separated_Logs.txt](https://github.com/logpai/logparser/files/3305498/Pipe_Separated_Logs.txt)
[Same_Pattern_logs.txt](https://github.com/logpai/logparser/files/3305499/Same_Pattern_logs.txt)

The Same pattern log file is interesting one as the pattern of log files is same but it still generates 2 different templates. This is because they have few extra tokens. 
I read in the Drain Algo research paper that most log events have the same tokens and if they aren't then there's a way these can be handled in post processing. Can you please suggest what and how can we add post processing here to get the same patterns getting attched to same log group?

**Comment by kokonguyen191** [comment]
https://github.com/logpai/logparser/blob/8f1f1face2c0e270fd9bcecdefe37ebc6ba76e9d/logparser/Drain/Drain.py#L260

This line seems to be the line that split logs using whitespace characters. You can try replacing `split()` with `split("|")` to see if it suits your use case.

**Comment by AnkitNassa** [comment]
The problem in my case is i have different log sources where most of them are space separated while some of them have these special characters like pipe or comma separated. Is there any way i can handle this at runtime which works for all kind of patterns?

Also for my second query, Same pattern log, can you comment on how to make it same template group?

**Comment by PinjiaHe** [comment]
You could define different delimiters for different log sources. Another option is to define multiple delimiters:
```python
# delimiters for white space, "=", and ":"
delimiters = '=|:|\s+'
wordL = re.split(delimiters, logmessage.strip())
```
For the same pattern log with extra tokens, you could merge different templates/log groups by comparing the template strings. If two templates are similar, their corresponding groups could be merged into one group.

**Comment by AnkitNassa** [comment]
Hi @PinjiaHe ,

For the same pattern log with extra tokens case.... **Can you please help me on how to merge different templates/log groups by comparing the template string** 
For instance:
1) A=a B=b C=c D=d(length 4)
2) A=a' a B=b' b C=c' c D=d' d(length 8)

The above 2 log lines belong to different first layer node length 4 and length 8 respectively. What part of code should we modify to handle these cases? As per my understanding we create the first layer based on token and later look for templates matching the log line and create if it isn't existing. But we search for template in same bucket of first layer node and not all the buckets to improve performance.

Appreciate your help in this :)

**Comment by PinjiaHe** [comment]
> But we search for template in same bucket of first layer node and not all the buckets to improve performance.

Right, but if you want to merge two groups, you need to add some code to link two groups to a single group (i.e., add another layer). In this case, they will output the same template. This may need some coding effort. We have implemented similar methods in 
https://github.com/logpai/logparser/blob/68b638dff17d824d264bb304e32b22a8d398f498/logparser/Drainjournal.py#L342-L372

If all your logs are in the format of "A=a B=b ...", we would suggest finding "A, B, ..." first by inspecting word frequency.

**Comment by AnkitNassa** [comment]
Hi @PinjiaHe 
Thanks for the reply. Is there any doc which explains what exactly is done in DrainJournal? Also why was this approach of getting a similar cluster not done in Drain as compare to DrainJournal... Was there any performance cost or some logical issue?

**Comment by PinjiaHe** [comment]
A draft could be found [here](https://arxiv.org/abs/1806.04356).

We did not implement it in Drain (ICWS17) because most of the logs we encountered can be handled without merging the groups. Additionally, it's possible for the merging mechanism to wrongly merge two groups, leading to other parsing errors. Thus, a suitable parameter is important.

**Comment by AnkitNassa** [comment]
Thanks @PinjiaHe . I shall try out the suggestions you have given against my log files and see how it goes. One last query i have is that currently creates a new Root Node and new logCluL for each log file. Is there any way where we can make it global and have one root node and maintain 1 logCluL for all the logs and log files we parse through Drain?

**Comment by PinjiaHe** [comment]
The easiest way is to merge the log files first. 

You could also modifier the _log_to_dataframe_ method to let it accept a list of file names as parameters, and read them all.
https://github.com/logpai/logparser/blob/8f1f1face2c0e270fd9bcecdefe37ebc6ba76e9d/logparser/Drain/Drain.py#L298-L315
