### ISSUE TITLE
OpenStack testing

### ISSUE THREAD

**Issue by psychogyiokostas** [logpai/logparser#36]
Hello,

Regarding Loglizer:

1. I run the Drain preprocessing on the Openstack_2k.log but i get different structured and templates csv files in comparison with the ones you have in path logparser/logs/OpenStack. I used Drain.py and run the script benchmark/Drain_benchmark.py.

2. I cannot find any dataloader.py for OpenStack similarly to HDFS. Can you provide this?

A sample of my generated structured csv can be seen here:
https://pastebin.com/LarMQwpd

and generated templates csv:
https://pastebin.com/2BBxLzv2

Thank you for your time.

**Comment by jimzhu** [comment]
1. The templates and structured csv in logparser/logs/OpenStack are groundtruth files used for accuracy evaluation. We use Drain + some manual postprocessing to get them.

2. We have the plan to implement data loaders for other datasets besides HDFS. But currently we are in hurry for other projects. Maybe later we can provide them.

**Comment by wolfVbx** [comment]
@psychogyiokostas have you solved the problem,I also encounter this problem,and I have no idea of sloving it.If u figout it out,would u mind share the code with me,or the workflow，thx!
