### ISSUE TITLE
Is there any way to upload templates before going ahead of parsing in Drain?

### ISSUE THREAD

**Issue by AnkitNassa** [logpai/logparser#39]
Hi Team,

I have a use case where i need to upload/reload few templates before i proceed to parse the logs. These templates are generated by Drain on running against a particular set of events. And now i would like to reload those templates before going to parse another batch of events. Could you suggest some ways to do this?

**Comment by AnkitNassa** [comment]
@PinjiaHe @jimzhu Could you please throw some lights on this?

**Comment by AnkitNassa** [comment]
Also browsing the pull request, i saw someone is actually trying to achieve the same thing in the commit: https://github.com/logpai/logparser/pull/30/commits. Can you please confirm if my understanding is correct

**Comment by jimzhu** [comment]
A quick solution is to use your existing templates to filter the logs. After this, you can train new templates with the remaining log data.
