### ISSUE TITLE
Templates of LogMatch question

### ISSUE THREAD

**Issue by psychogyiokostas** [logpai/logparser#42]
Hi,

I am running the LogMatch log parser using the sample files that you have (HDFS_2k.log).

I understand that you match the templates that you give as input to the log parser with the log lines and generate structured logs. But, how did you obtain this HDFS_2k.log_templates.csv file if you use it as input to the log parser? 

Also, I after log parsing the HDFS_2k.log the templates I get as output (HDFS_2k.log_structured.csv), differ from the ones you have. Am I missing anything?

Thank you for your time.

**Comment by jimzhu** [comment]
HDFS_2k.log_templates.csv is made manually. It is used for accuracy evaluation only. The file is not needed (as shown in demos) when you parse log files. But you need this ground truth file for accuracy calculation (as shown in benchmarks).

**Comment by jimzhu** [comment]
The automated parsed file is not 100% correct. So it is different with the ground truth file.
