### ISSUE TITLE
tuning param for RegexMatch

### ISSUE THREAD

**Issue by psychogyiokostas** [logpai/logparser#44]
Hello,

If workers >1 what this really does is processing the raw file in parallel faster i suppose - with respect to RegexMatch log parser.
I would like to ask if there is any parameter for the above log parser, which we can tune so that we can change the number of templates we get?

Thank you.

**Comment by jimzhu** [comment]
The regex match parser is designed to transform raw logs into sturctured logs, when event templates are given.
