### ISSUE TITLE
python 3.7 ‘s re module is incompatible with the code

### ISSUE THREAD

**Issue by dorianxiao** [logpai/logparser#45]
python 3.7 ‘s **re** module is incompatible with the code，I found a solution, just change the code `import re` to `import regex as re`，but should `pip3 install regex` in command line first. 
The previous error is as follows:
![image](https://user-images.githubusercontent.com/21002283/64316438-65926a00-cfe7-11e9-8106-64dad59722ae.png)

**Comment by jimzhu** [comment]
Thanks for your reporting. But we plan to only support python 2.7 for easy of maintainance.
