### ISSUE TITLE
Unable to reproduce running time of parsing method. 

### ISSUE THREAD

**Issue by Wandefear** [logpai/logparser#46]
Hello, 

I am trying to reproduce your results about the running time provided by your paper on Drain (extended version) https://arxiv.org/pdf/1806.04356.pdf.
Unfortunately, I cannot reproduce the results for the running time of the IPLoM and Spell method. Indeed, I am supposed to find a running time of 447.14s for the Spell method and 140.57s for the IPLoM method. Using your implementation of IPLoM and Spell and the provided parameters by your benchmark tools, I find 817s for the IPLoM method and 34339s for the Spell method.

Do you have any idea where I did something wrong?

**Comment by jimzhu** [comment]
I think you should remove IO time as reported in the paper

**Comment by Wandefear** [comment]
Thanks for your quick answer. 
I forgot to mention that the loading time of the entire BGL dataset into the memory is about 40s on my system. 
Even if I consider a longer loading time on your system, the difference for the Spell method is more than 76x. In your paper, did you use the implementation released in your benchmark tool? Or another implementation?

**Comment by PinjiaHe** [comment]
You may try this: https://github.com/logpai/logparser/blob/dev/logparser/Spell.py

This is the one we used, but theoretically, the differences should only be the IO process.

**Comment by jimzhu** [comment]
The current benchmark is a later version.  Some regex is added to generate structure_log. csv, which is not available in previous version.  You can only calculate the core algo time.

**Comment by Wandefear** [comment]
Using the code @PinjiaHe provided: 

I add the " lines = lines.readlines()" just before "for line in lines:" line 281 for avoiding IO process in the following lines. Now, all the dataset is loaded in my RAM after the "lines.readlines()"
Then I start a timer() just after "lines = lines.readlines()" and just before the "for line in lines:"

After 30 minutes of calculation, Spell analyzed only 50500 lines of logs (end expected in 45 hours.) 

@jimzhu For the moment, I am focused only on the execution time. I can reproduce your accuracy results without any issue on small dataset.

**Comment by jimzhu** [comment]
IO time is not only about data reading, but also dumping output files.

**Comment by Wandefear** [comment]
I agree with you, but the dumping of the output files is at the end of the algorithm (self.outputResult). The result I gave previously is only the running time (the Spell algorithm is currently running on my computer). The outputResult is commented. 

I forgot also to mention my hardware: 2 x Intel(R) Xeon(R) CPU E5-2660 / 128 GB of RAM / 6 TO of hard drive.

**Comment by PinjiaHe** [comment]
Did you follow the related [quick-start instructions](https://github.com/logpai/logparser/tree/dev#quick-start) on running the code? This may help.

**Comment by Wandefear** [comment]
Sure, I read it. 
For starting the code provided by  @PinjiaHe, I write:
```
RawLogPath` = '/root/data/logs_various/'
RawLogFile = 'BGL.log'
removeCol = [0,1,2,3,4,5,6,7,8]
rex = [('core\.\d+')]
mt = 1
delimiters = " "
OutputPath = './results/'
para = Para(path=RawLogPath, logName=RawLogFile, savePath=OutputPath, rex=rex, tau=0.75, removeCol=removeCol)

myparser = Spell(para)
_ = myparser.mainProcess()
```

And I update the beginning of the mainProcess following the Drain implementation:
 ```
                logID = index
                index += 1
                logmessageL = line.strip().split(' ')[9:]
                cookedLine = ' '.join(logmessageL)
                for currentRex in self.para.rex:
                    cookedLine = re.sub(currentRex[0], currentRex[1], cookedLine)

                constLogMessL = [w for w in cookedLine if w != '*']

                # Find an existing matched log cluster
                matchCluster = self.PrefixTreeMatch(rootNode, constLogMessL, 0, len(logmessageL))
```

If I am doing something wrong, could you provide me an full implementation of the Spell parser where I just need to update the path according to my system to get the same execution time as you?
