### ISSUE TITLE
POP Implementation

### ISSUE THREAD

**Issue by zakariafik** [logpai/logparser#47]
Hi,

Thank you for the good quality content, very well organised repo 👍.
On this paper http://jmzhu.logpai.com/pub/pjhe_tdsc2017.pdf, it is mentioned that the implementation of POP is in this repo. Can you point me to where is it because I can't find it.

Thanks a lot!

**Comment by PinjiaHe** [comment]
Thanks for your interest in our project! The POP implementation could be found [here](https://github.com/logpai/logparser/blob/dev/logparser/POP/POP.py).
