### ISSUE TITLE
How do you generate the templates.txt under data/?

### ISSUE THREAD

**Issue by lhzw** [logpai/logparser#5]
How do you generate the templates.txt under data?
Seems the template is good, but I don't know how to generate it with my own log, and how to use it, thanks.

**Comment by PunyTitan** [comment]
Hi,

We generate templates.txt, which is the ground truth, by manual inspection.
Specifically, we manually construct regular expression based on the raw
logs, and use scripts to separate them to different groups.

You could also use our tool to parse the logs. The output of the log parser
contains a template file. It is feasible to transform these templates found
by our parser to regular expressions with ad-hoc scripts.


Regards,
Pinjia

**Comment by jimzhu** [comment]
@lhzw Please refer to our new development branch for a demo.  https://github.com/logpai/logparser/tree/dev
