### ISSUE TITLE
Can you provide a demo of Drian for dealing with BGL dataset? 

### ISSUE THREAD

**Issue by sunpeijie0** [logpai/logparser#55]
Hello! For my near study, I want to use excellent configuration of Drain for dealing with BGL dataset. Can you provide some configuration or code?

**Comment by HankKung** [comment]
same. I used configs in the benchmark but got 1800+ log templates.

**Comment by PinjiaHe** [comment]
The parameters used can be found in our paper:
https://pinjiahe.github.io/papers/ICWS17.pdf

Specifically, Table II and the paragraph behind introduce the parameters and preprocessing details on different datasets.

**Comment by XingfangWu** [comment]
Hello,

I just want to share my regex setting for the BGL dataset. With this setting, the amount of templates drops to 337 with the parameters recommended by the aforementioned paper.

`
regex      = [r'core\.\d+',
              r'(?<=r)\d{1,2}',
              r'(?<=fpr)\d{1,2}',
              r'(0x)?[0-9a-fA-F]{8}',
              r'(?<=\.\.)0[xX][0-9a-fA-F]+',
              r'(?<=\.\.)\d+(?!x)',
              r'\d+(?=:)',
              r'^\d+$', 
              r'(?<=\=)\d+(?!x)',
              r'(?<=\=)0[xX][0-9a-fA-F]+',
              r'(?<=\ )[A-Z][\+|\-](?= |$)',
              r'(?<=:\ )[A-Z](?= |$)',
              r'(?<=\ [A-Z]\ )[A-Z](?= |$)']
`

**Comment by X-zhihao** [comment]
> Hello,
> 
> I just want to share my regex setting for the BGL dataset. With this setting, the amount of templates drops to 337 with the parameters recommended by the aforementioned paper.
> 
> `regex = [r'core\.\d+', r'(?<=r)\d{1,2}', r'(?<=fpr)\d{1,2}', r'(0x)?[0-9a-fA-F]{8}', r'(?<=\.\.)0[xX][0-9a-fA-F]+', r'(?<=\.\.)\d+(?!x)', r'\d+(?=:)', r'^\d+$', r'(?<=\=)\d+(?!x)', r'(?<=\=)0[xX][0-9a-fA-F]+', r'(?<=\ )[A-Z][\+|\-](?= |$)', r'(?<=:\ )[A-Z](?= |$)', r'(?<=\ [A-Z]\ )[A-Z](?= |$)']`

hello，can I have you email？I have several easy questions which l think you can solve. Best wishes

**Comment by Tan3364** [comment]
Hi, I have recently used Drain for Log Parsing.  Could someone share excellent configurations for the Spirit and Thunderbird dataset?

Best Wishes,
Xiao Tan
