### ISSUE TITLE
Installation procedure

### ISSUE THREAD

**Issue by senovr** [logpai/logparser#59]
Hi, 
I have two questions about logparser.

First, the installation procedure is absent.
I can not find a clear installation procedure using conda/pip. Can you please share one?

Second, support of python 3+.
2.7 is approaching EOL, and it seems natural for me to have compatibility with the current version of python.

Thanks for your comments in advance!

**Comment by davidohana** [comment]
If you use Drain, you might want to try Drain3 - a wrapped Drain implementation that solves exactly those issues - it's adapted to Python3 and packaged for pip.

https://github.com/IBM/Drain3

**Comment by zraiss** [comment]
@senovr I have  seem question, I want to test Logparser but I don't know how!
