### ISSUE TITLE
Docker run issue

### ISSUE THREAD

**Issue by Anny2131** [logpai/logparser#62]
![image](https://user-images.githubusercontent.com/34367108/93762716-c0682500-fc2d-11ea-98a8-751a14582184.png)
Getting above error while running docker image

**Comment by Anny2131** [comment]
worked

**Comment by skylaanne** [comment]
> worked

I am having the same error, would you be able to point me in the right direction in how you solved this issue? Thank you!

**Comment by anjali-bhavan** [comment]
Hey how was this fixed? Thank you!
