### ISSUE TITLE
Not able to reproduce results using benchmark

### ISSUE THREAD

**Issue by DeepaliBhanage** [logpai/logparser#67]
Hello,
I am trying to run a benchmark file for a spell as well as a drain but getting error as " ImportError: cannot import name 'Spell' from 'logparser' (C:\Users\Dell\anaconda3\lib\site-packages\logparser\__init__.py)
"
Please guide me how to handle this error. I have created an environment as said in the instructions.

**Comment by PinjiaHe** [comment]
Thanks for your interest in our project. 

It is possible that you didn't put the parser files in the right path. 

You could also take a look at the doc. to check the dependencies: https://logparser.readthedocs.io/en/latest/installation/dependency.html

**Comment by DeepaliBhanage** [comment]
Thank you for quick response.
Please tell me what is default/ right path to place parser.
I have clone all files in C drive.

**Comment by PinjiaHe** [comment]
Usually, that should work. After git clone the repo., run 
```
$cd /logparser/demo/
$python Spell_demo.py
```

If that doesn't work, you could try with Python 2.7, or use the docker images as mentioned in our [document](https://logparser.readthedocs.io/en/latest/demo.html).

Hope it helps.

**Comment by DeepaliBhanage** [comment]
Yes. It's working.....
Thank you so much for your help
