### ISSUE TITLE
Install as a python package

### ISSUE THREAD

**Issue by chauhankaranraj** [logpai/logparser#69]
Hi,

I really like how this repo provides a collection of open source tools for analyzing logs, and wanted to explore these tools in detail. However after reading the docs, it is not entirely clear to me how I can install this repo/library as a python package, outside of Anaconda.

So far, I have tried the following:
1. `pip install git+https://github.com/logpai/logparser.git@e8d96cd4de1121c5d2b517982c6028cd06e643f1`: this throws an error because `setup.py` is missing
2. `pip install logparser`: this [package name on pypi](https://pypi.org/project/logparser/) does not correspond to this project

Could the authors please suggest how to install this library as a python package?
Also, would it be a good idea to [publish this repo as a package on pypi](https://packaging.python.org/tutorials/packaging-projects/) so that others can just `pip install` these tools?

I'm happy to help with any step, if needed.

Thanks in advance! :)

**Comment by PinjiaHe** [comment]
Hi,

Thanks for your interest and suggestions! 

Currently, our project cannot be installed as a python package. We plan to do so in the near future. Typically, to use the toolkit, you could download the repo. and go to the benchmark folder.

You may find some useful discussion here: https://github.com/logpai/logparser/issues/67#issuecomment-808324473_

**Comment by chauhankaranraj** [comment]
> Typically, to use the toolkit, you could download the repo. and go to the benchmark folder.
> 
> You may find some useful discussion here: [#67 (comment)](https://github.com/logpai/logparser/issues/67#issuecomment-808324473)

Thanks for pointing me here :) I'm able to run the scripts this way, but imho packaging this toolkit and `import`-ing it as a python library would be a more "ideal" workflow.

> Currently, our project cannot be installed as a python package. We plan to do so in the near future.

That's great to hear! Is there a rough estimate on when this will be done by? Also, if you're looking for any help with this, I'm happy to contribute.

**Comment by PinjiaHe** [comment]
> That's great to hear! Is there a rough estimate on when this will be done by? Also, if you're looking for any help with this, I'm happy to contribute.

We plan to do this later this year. We will be happy if you'd like to contribute to our project.
