### ISSUE TITLE
Could I use a trained template to parse new logs？

### ISSUE THREAD

**Issue by TahoeWang** [logpai/logparser#70]
As you know, when you parse some logs, you get a trained template at the same time. but when you parse new logs, how to keep the parsing results the same？Could I use a trained template to parse new logs？

**Comment by PinjiaHe** [comment]
You could keep using the parse tree (for online parsers) by storing the tree somewhere and then load it the next time. Another feasible way could be to slightly modify the template as regular expressions and use the regex.
