### ISSUE TITLE
raise KeyError in Drain

### ISSUE THREAD

**Issue by sueliangliang** [logpai/logparser#79]
![image](https://user-images.githubusercontent.com/50368004/149111594-103f8115-174d-4474-b139-57d8231c6bb7.png)

**Comment by JinYang88** [comment]
Could you please provide more details? For example, which log file you are running?

**Comment by znagzanglong** [comment]
Why does EventId resolve to some weird symbols. For example:
![image](https://github.com/logpai/logparser/assets/103175176/7c628bb4-0a87-4009-9f1b-f5d9f23c5bab)
