### ISSUE TITLE
bad escape \s in Drain.py

### ISSUE THREAD

**Issue by moesjo** [logpai/logparser#84]
When running the demo script for drain to following error occures:
`re.error: bad escape \s at position 2`
Changing line 339 in Drain.py from
`template_regex = re.sub(r'\\ +', r'\s+', template_regex)`
to
`template_regex = re.sub(r'\\ +', r'\\s+', template_regex)`
fixed the problem for me.

**Comment by moesjo** [comment]
Already included in several pull requests.

**Comment by moesjo** [comment]
I think for spell it's pretty much the same, there should be a line similar to the one shown above and when you fill in the `\` it should work.
Maybe you should also consider using one of the forks of this project, there are some which already include the fixes for these issues (see pull-requests).

**Comment by shoaib-intro** [comment]
> I think for spell it's pretty much the same, there should be a line similar to the one shown above and when you fill in the `\` it should work.
> Maybe you should also consider using one of the forks of this project, there are some which already include the fixes for these issues (see pull-requests).

Thanks for reply but I even tried to change drain parameter code with spell does not works....even tried to change concerning line as well....spell keeps working for days but does not bring any output

**Comment by moesjo** [comment]
So i looked it up and from the syntax point of view you only have to change line 312 in Spell.py from

        splitter = re.sub(' +', '\s+', splitters[k])
to

        splitter = re.sub(' +', '\\\s+', splitters[k])

**Comment by shoaib-intro** [comment]
> So i looked it up and from the syntax point of view you only have to change line 312 in Spell.py from
> 
> ```
>     splitter = re.sub(' +', '\s+', splitters[k])
> ```
> 
> to
> 
> ```
>     splitter = re.sub(' +', '\\\s+', splitters[k])
> ```

I have already tried this one, this works but only parameters extraction does not work however it works some other part of dataset but on some dataset having same size does not extract parameters.

**Comment by moesjo** [comment]
Okay, unfortunately I can't help you with this problem but i hope you'll find a fix for that!
