### ISSUE TITLE
Generating the ground truth data

### ISSUE THREAD

**Issue by damucka** [logpai/logparser#9]
Hello,

I plan to use the drain algorithm for the processing of my logs. l used it and it works fine, generating structured and the template files. Now I would like to check the quality of the template using your evaluation program and here I need your guidance. It expects the groundtruth files as an input. The question is how would I generate them at easiest. My plan would be to use your drain parser to generate the structured data and then take the message part of it, group e.g. in Excel and assign the event IDs to each distinct group. 
Would that be a reasonable approach?

Kind Regards 
Kamil

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by PunyTitan** [comment]
Hi Kamil,

After obtaining the template files, you can generate a list of regular expressions based on the mined templates. Then you can use the regular expressions to separate the raw logs. Some raw logs may not be matched by any regular expressions, for those (often only a few), you could manually construct regular expressions for them.

Regards,
Pinjia
