### ISSUE TITLE
Unable to figure out how to use the logparser

### ISSUE THREAD

**Issue by ganeshkamath89** [logpai/logparser#97]
I have downloaded the logparser project on my system. I don't see build steps or any documentation on how I can utilize the logparser to parse logs on my system. Can you please add a section in the Readme.md or some other place where we can learn how to use the tools available in this site

I see a file __init__.py

Is there some set of instructions to help me build the repository and exeucute the python files from the demo folder?

**Comment by JinYang88** [comment]
Please follow the instructions in our demo page.

https://logparser.readthedocs.io/en/latest/demo.html

**Comment by berot3** [comment]
@ganeshkamath89 how did it go? Just wondering.
